# Generated by Django 5.1 on 2024-09-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outros"),
                        ],
                        max_length=1,
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="TipoExame",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Exame",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("observacao", models.CharField(max_length=255)),
                (
                    "tipo_exame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_hospital_consulta.tipoexame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_hora", models.DateTimeField()),
                (
                    "protocolo",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "exame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_hospital_consulta.exame",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_hospital_consulta.paciente",
                    ),
                ),
                (
                    "tipo_exame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_hospital_consulta.tipoexame",
                    ),
                ),
            ],
        ),
    ]
